Devfolio-team/Devfolio-Client

- src/components/index.js
Close #11 
- components 폴더 내 index.js에 Button component를 export하는 코드 작성
> Components 폴더내 index.js 변경

- src/utils/index.js
Close #12 
- utils 폴더 내 index.js에 color.js를 export하는 코드 작성
> utils 폴더내 index.js 변경

- src/components/Button/Button.js
Close #13
- Button component내의 hex code color들 color.js의 변수들로 변경
> Button component내의 hex code color들 color.js의 변수들로 변경

- src/components/Heading/Heading.js
- src/components/Heading/Heading.stories.js
- src/components/index.js
Close #1 
-  Heading component 생성
> feat: Heading Component 생성

- src/components/index.js
- index.js에 RadioButton 컴포넌트 export 추가
> index.js에 RadioButton 컴포넌트 export 추가

- src/components/Input/Input.js
- src/components/Input/Input.stories.js
- src/components/index.js
Close #2 
- Input component 와 스토리북 생성 및 index.js에 Input component export 추가
> Input Component와 스토리북 생성

- src/components/Paragraph/Paragraph.js
- src/components/Paragraph/Paragraph.stories.js
- src/components/index.js
Close # #5 
- Paragraph 컴포넌트 생성
> feat: Paragraph 컴포넌트 생성

- src/components/Button/Button.js
Close #20
- Button Component의 storybook의 description에 안뜨던것 수정
> Button Component의 storybook의 description에 안뜨던것 수정

- src/components/Input/Input.js
- src/components/Input/Input.stories.js
Close #28
- Input Component에 label element 추가
> Input Component에 label element 추가

- src/components/Selectbox/Selectbox.js
- src/components/Selectbox/Selectbox.stories.js
- src/components/index.js
Close #30 
- Selectbox Component와 스토리북 생성 및 index.js에 Selectbox export 추가
> Selectbox Component와 스토리북 생성

- src/components/TextArea/TextArea.js
- src/components/TextArea/TextArea.stories.js
- src/components/index.js
Close # #4 
- TextArea 컴포넌트 생성
- TextArea 스토리북 생성
- index.js에 TextArea 컴포넌트 import 추가
> TextArea 컴포넌트 생성

- src/components/Input/Input.js
- src/components/Input/Input.stories.js
Close #47 
-  Input Component의 placeholder 대신 label styling을 이용, mode라는 prop을 만들어 숨김 가능 구현
> Input component 리팩토링

- src/components/Button/Button.js
- src/components/Button/Button.stories.js
- src/components/Image/Image.js
- src/components/Image/Image.stories.js
- src/components/Input/Input.js
- src/components/Input/Input.stories.js
- src/components/RadioButton/RadioButton.stories.js
- src/components/Selectbox/Selectbox.stories.js
Close #62 
- Button, Image, Input Component의 styled components에 css명과 같은 attritbute를 props로 할당했을때 그대로 적용되는 버그를 고치고 추가로 위의 컴포넌트들에 더해서 Radiobutton, Selectbox 컴포넌트의 storybook description과 argTypes들을 수정했습니다.
> Button, Image, Input Component의 styled components 수정 및 스토리북 수정

- src/components/Dialog/Dialog.js
- src/components/Input/Input.js
- src/components/Logo/Logo.stories.js
- src/components/Modal/Modal.js
- src/containers/HeaderBar/HeaderBar.js
- src/containers/LoginModalDialog/LoginModalDialog.js
- src/containers/SignupModalDialog/SignupModalDialog.js
- src/containers/index.js
- src/utils/color.js
Close # #69 
- placeholder 폰트 색 변경
- Dialog 화면 중앙배치
- SignupModalDialog Component 생성(storybook 추가예정 파일만 만듬)
- LoginModalDialog Component 수정
-  placeholder 대신 사용한 label 수정 
- Logo storybook 수정
- Modal Component height 속성 추가 
- SignupModalDialog Component 추가
> SignupModalDialog Component 생성

- src/components/Input/Input.js
- src/components/Input/Input.stories.js
- src/components/ProjectName/ProjectName.js
- src/components/ProjectName/ProjectName.stories.js
- src/components/RadioButton/RadioButton.js
- src/components/RadioButton/RadioButton.stories.js
- src/components/Selectbox/Selectbox.js
- src/components/Selectbox/Selectbox.stories.js
- src/components/index.js
Close #71
Close #80
Close #79
Close #81 
- 프로젝트 이름 컴포넌트 생성 및 스토리북 생성
- 수정해야될 부분: Input 컴포넌트를 사용하는 부분에서 box-shadow를 수정해야됨 (수혁님의 모달 다이얼로그의 input의 box-shadow fixed 해놓은 문제 수혁님과 소통후해결 필요)
- RadioButton 컴포넌트 상태 관리 중점으로 리팩토링하고 스토리북도 그에 대한 변경 사항 리팩토링
- Input 컴포넌트 상태 관리 중점으로 리팩토링하고 스토리북도 그에 대한 변경 사항 리팩토링
- Selectbox 컴포넌트 상태 관리 중점으로 리팩토링하고 스토리북도 그에 대한 변경 사항 리팩토링
> 프로젝트 이름 컴포넌트 생성, RadioButton 컴포넌트 리팩토링, Input 컴포넌트 리팩토링, Selectbox 컴포넌트 리팩토링

- src/components/ChipInputSearch/ChipInputSearch.js
- src/components/ChipInputSearch/ChipInputSearch.stories.js
- src/components/DND/DND.js
- src/components/DND/DND.stories.js
Close #83 
Close #82 
- ChipInputSearch 컴포넌트 상태 관리 중점으로 리팩토링하고 한 컴포넌트로 볼것으로 정하고 스토리북도 그에 대한 변경 사항 리팩토링
- DND 컴포넌트 상태 관리 중점으로 리팩토링하고 한 컴포넌트로 볼것으로 정하고 스토리북도 그에 대한 변경 사항 리팩토링
> ChipInputSearch 컴포넌트 리팩토링, DND 컴포넌트 리팩토링

- src/components/ProjectName/ProjectName.js
- src/components/ProjectName/ProjectName.stories.js
Close #89 
- Input 컴포넌트를 상태 관리하기 위해 리팩토링 한 것을 이용하여 Input 컴포넌트를 사용한 ProjectName 컴포넌트 리팩토링 (value, onChange 추가)
> ProjectName 컴포넌트 리팩토링

- src/components/Button/Button.js
- src/components/Dialog/Dialog.js
- src/components/Input/Input.js
- src/containers/HeaderBar/HeaderBar.js
- src/containers/LoginModalDialog/LoginModalDialog.js
- src/containers/SignupModalDialog/SignupModalDialog.js
Close # #84 
- LoginModalDialog 접근성, 반응형 추가
> Feat: LoginModalDialog 접근성, 반응형 추가

- src/components/ProjectName/ProjectName.js
- src/components/ProjectName/ProjectName.stories.js
- src/components/RadioButton/RadioButton.js
- src/components/RadioButton/RadioButton.stories.js
- src/components/TeamName/TeamName.js
- src/components/TeamName/TeamName.stories.js
Close #78 
- TeamName 컴포넌트 생성 및 스토리북 작성
- RadioButton의 margin값 적용하게 코드 추가
- ProjectName 컴포넌트에서 props로 받던 id값 props로 받지 않고 그냥 넣어줌
> TeamName 컴포넌트 생성, RadioButton과 ProjectName 컴포넌트 코드 일부 수정

- src/components/GithubLink/GithubLink.js
- src/components/GithubLink/GithubLink.stories.js
- src/components/Paragraph/Paragraph.stories.js
- src/components/index.js
Close # #94 
- GithubLink Component 생성
- GithubLink storybook 생성
- index.js에 GithubLink import 추가
- Paragraph storybook 이름 잘못 적혀있는 것 수정
> Feat: GithubLink Component 생성

- src/components/Button/Button.js
- src/components/Input/Input.js
- src/components/RadioButton/RadioButton.js
- src/components/Selectbox/Selectbox.js
Close #99 
- Input 컴포넌트의 propTypes에서 string과 number 둘 다 받와야되는 props에 oneOfType적용
- TechStacks 컴포넌트 생성 및 스토리북 작성
> Input 컴포넌트의 propTypes 수정 및 TechStacks 컴포넌트 생성 및 스토리북 작성

- src/components/Button/Button.js
- src/components/Dialog/Dialog.js
- src/components/GithubRepoInput/GithubRepoInput.js
- src/components/GithubRepoInput/GithubRepoInput.stories.js
- src/components/Heading/Heading.js
- src/components/Input/Input.js
- src/components/Paragraph/Paragraph.js
- src/components/SVGIcon/SVGIcon.js
- src/components/index.js
- src/containers/LoginModalDialog/LoginModalDialog.js
Close # #111  #112 
- GithubLink -> GithubRepoInput 이름수정
-  input label에 반응형으로 fontsize 수정 
- GithubLink Component 이름 수정 
-  콘솔창에 waring 생기는 현상 수정 …
> Refactor: 콘솔창에 waring 현상 수정, 반응형 수정

- src/components/Container/Container.js
- src/components/SkillIcon/SkillIcon.js
- src/containers/LoginModalDialog/LoginModalDialog.js
- src/pages/Project/ProjectPage.js
Close # #138
- SkillIcon에서 props로 width와 height props 삭제
- ProjectPage에서 좋아요 버튼 애니메이션 구현
- ProjectPage에서 팀원목록을 아직 구현하지 않아서 console.log에 나오는 waring을 지우기위해서 코드 주석처리
- LoginModalDialog에서 모달의 로그인버튼에서 배경색이 안나오는 오류와 아이콘과 글자 재정렬
> ProjectPage Component 좋아요 버튼 애니메이션 추가

- src/pages/Project/ProjectPage.js
Close # #158 
- Project Component 에서 Styled~로 시작하는 컴포넌트들 명시적으로 이름 변경
> Refactor: Project Component 이름수정

- src/components/GithubRepoInput/GithubRepoInput.js
- src/utils/validationSchema.js
Close #181 
- GithubRepo validation이 완벽히 거르지 못한 버그 해결 (정규표현식 수정)
> GithubRepo validation이 완벽히 거르지 못한 이슈 해결

- src/components/ProjectExplanation/ProjectExplanation.js
- src/containers/HeaderBar/HeaderBar.js
- src/containers/LoginModalDialog/LoginModalDialog.js
- src/pages/Project/ProjectPage.js
Close # #215 
- ProjectExplanation 스타일링 수정
li요소의 점 부분을 문단 안쪽으로 들여오는 스타일로 변경
-  LoginModalDialog 생성 시 스크롤 방지기능 추가 
-  LoginModalDialog 디자인 수정 
모바일에서 X버튼 깨지는 현상 수정
디자인 최종 시안으로 수정
-  ProjectPage 디테일 수정
네비게이션에서 글 제목이 길어지면 옆으로 늘어지는 현상 수정
모바일 뷰에서 제목, 팀 이름 간격 수정
좋아요의 count가 0일 때 버튼이 생기지 않는 오류 수정
프로필사진, 이름 누르면 해당 유저 페이지로 이동하게 끔 수정
> ProjectPage, LoginModalDialog, ProjectExplanation 수정

- src/pages/Project/ProjectPage.js
modified:   src/pages/Project/ProjectPage.js
Close # #219
-  스켈레톤 UI 수정
> BugFix: 스켈레톤UI 수정

- src/pages/PortfolioEdit/PortfolioEditPage.js
Close #
- 포트폴리오 수정 페이지에서 깃헙 로그인시 이메일 validation오류 나는 버그 수정
> 포트폴리오 수정 페이지에서 깃헙 로그인시 이메일 validation오류 나는 버그

- src/components/ProjectExplanation/ProjectExplanation.stories.js
- src/containers/LoginModalDialog/LoginModalDialog.stories.js
- src/containers/ModalDialog/ModalDialog.stories.js
- src/pages/Project/ProjectPage.js
Close: # #250 
- ProjectPage 좋아요버튼 마크업 순서 변경 및 스타일링 수정 
-  ProjectExplanation 스토리북 생성
-  LoginModalDialog, ModalDialog 스토리북 수정 …
> Refactor: Storybook 수정 및 추가, ProjectPage 좋아요 마크업, 스타일 수정

- src/components/PlanIntention/PlanIntention.js
- src/pages/Project/ProjectPage.js
Close: #
- 프로젝트 수정 및 조회 페이지에서 기획의도라는 타이틀을 기획 의도 및 소개라고 변경 및 타이틀 밑에 간략한 소개글 작성
> 프로젝트 수정 및 조회 페이지에서 기획의도라는 타이틀을 기획 의도 및 소개라고 바꿔주기

- src/components/EmptyMessage/EmptyMessage.js
- src/components/EmptyMessage/EmptyMessage.stories.js
- src/components/index.js
- src/containers/HeaderBar/HeaderBar.js
- src/containers/PortfolioContents/PortfolioContents.js
- src/containers/UseTechStacks/UseTechStacks.js
- src/pages/FavoriteProject/FavoriteProjectPage.js
- 원래 프로젝트 페이지, 포트폴리오 페이지에서 중복으로 생성하여 사용하던 EmptyMessage라는 컴포넌트를 재사용하기 위해 하나의 파일에서 컴포넌트로 생성하여 모듈화 하여 3군데서 사용하게끔 변경하였습니다.
> Refactor: 좋아요한 프로젝트가 없을시에 무한으로 스켈레톤 UI가 뜨던 이슈 해결

- src/app/App.js
- src/pages/Home/HomePage.js
- src/pages/ProjectEdit/ProjectEditPage.js
- src/pages/index.js
- yarn.lock
Close: #324
- App컴포넌트에서 페이지별로 코드 스플리팅 적용
> App컴포넌트에서 페이지별로 코드 스플리팅 적용
